---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined

- name: Upgrade alembic
  command: docker exec -u root -e PYTHONPATH=. {{ application_name }} pipenv run alembic upgrade head
  register: command_output
  changed_when: command_output.rc != 0
