name: Ansible Lint

on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
      with:
        targets: "."
        args: ""
        override-deps: |
          ansible-lint==5.3.2
